#!/usr/bin/bash

for file in `find * -type f -iname "*.html"`
	do {
		mtime=`date -r $file +%Y%m%d%H%M.%S`;
		rm -rf $file".mtime";
		touch $file".mtime";
		# echo $mtime;
		echo $mtime > $file".mtime";
	} 
done;